### ISSUE TITLE
"Unexpected token error" with `vue add vuetify`

### ISSUE THREAD

**Issue by sarahLardeau** [vuetifyjs/vue-cli-plugins#141]
I encoutered an error on `vue add vuetify` command and managed to find a simple scenario to reproduce the issue.

Steps to reproduce :
- Create a new vue project with @vue/cli-services: 4.1.1 with this config (basic with typescript) : 
![image](https://user-images.githubusercontent.com/33665326/70524348-3e4abc00-1b45-11ea-8d7c-7a77ef5d4730.png)
- Add the following code in main.ts
`Vue.config.errorHandler = (err: Error, vm: Vue, info: string) => {
  // For some crash tracking config like Sentry
};`
![image](https://user-images.githubusercontent.com/33665326/70524753-20ca2200-1b46-11ea-9eb0-07b93d9d6734.png)

- Then run : `vue add vuetify` and select the default preset

You will see a nice parser error
![image](https://user-images.githubusercontent.com/33665326/70524679-f710fb00-1b45-11ea-8f9f-d5004784a431.png)

If you remove the code added to main.ts it works perfectly ;)

**Comment by johnleider** [comment]
I cannot reproduce this. Can you provide a repository?

**Comment by KaelWD** [comment]
Likely a bug with vue-cli itself: https://github.com/vuejs/vue-cli/issues/4861
