### ISSUE TITLE
[Bug Report] CLI generate wrong locale string

### ISSUE THREAD

**Issue by slime7** [vuetifyjs/vue-cli-plugins#148]
I select Chinese and it generate:

```js
lang: {
  locales: { zhHans },
  current: 'zh-Hans',
}
```

But it should be:

```js
lang: {
  locales: { zhHans },
  current: 'zhHans',
}
```

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
