### ISSUE TITLE
[Bug Report] Functionality to slide down to navigation list group item based on browser path

### ISSUE THREAD

**Issue by ratnakarp** [vuetifyjs/vue-cli-plugins#153]
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 7

### Steps to reproduce
I have setup the code in the above link. I'm trying to write the code in such a way that every time when i hit the book marked url, the navigation drawer should automatically slide to the respective list item, that means that it should open the parent(s) group as well. Can you please help in how i can i achieve that ? I tried many ways with the code below.

### Expected Behavior
Navigation drawer slides down automatically to the respective list item as per the browser path. for ex:http://localhost/securemessageinbox, will have the navigation drawer open the Member Research --> Secure Messaging --> Inbox

### Actual Behavior

As mentioned in steps to reproduce...

### Reproduction Link
<a href="https://codepen.io/ratnakarp/pen/ZEYPLGO" target="_blank"></a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
