### ISSUE TITLE
Specify variables location

### ISSUE THREAD

**Issue by hamishjohnson** [vuetifyjs/vue-cli-plugins#158]
According to https://vuetifyjs.com/en/customization/sass-variables#vue-cli-install

In order to specify your variable overrides, you must put it in a styles/scss/sass folder in the src. I would like to be able to specify where these styles are stored.

**Comment by XavierChevalier** [comment]
The change of path will be very useful!
To solve the problem temporarily, we had to create a `src/sass/variables.scss` file in which we have :
```scss
// ./src/sass/variables.scss

@import "./../assets/styles/settings/variables"; // Here, the true path to the stored file.
```
We are hoping for an option to avoid this.

**Comment by davydnorris** [comment]
See #187 for an additional bug related to this

**Comment by johnleider** [comment]
Duplicate of #187
