### ISSUE TITLE
how to use icons

### ISSUE THREAD

**Issue by naveenkash** [vuetifyjs/vue-cli-plugins#161]
how to use icons in stories template

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
