### ISSUE TITLE
[Bug Report]  select error

### ISSUE THREAD

**Issue by 1748839240** [vuetifyjs/vue-cli-plugins#162]
### Environment

**Browsers:** Chrome 80.0.3987.100
**OS:** Linux x86_64

### Steps to reproduce

The select component cannot be closed after selection

### Expected Behavior

The select component cannot be closed after selection

### Actual Behavior

The select component cannot be closed after selection

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by jacekkarczmarczyk** [comment]
Please use correct repository and properly fill in the issue form
