### ISSUE TITLE
[Bug Report]  select error

### ISSUE THREAD

**Issue by 1748839240** [vuetifyjs/vue-cli-plugins#163]
### Environment

**Browsers:** Chrome 80.0.3987.100
**OS:** Linux x86_64

### Steps to reproduce

The select component cannot be closed after selection v1.5.23

### Expected Behavior

The select component cannot be closed after selection v1.5.23

### Actual Behavior

The select component cannot be closed after selection v1.5.23

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/162
