### ISSUE TITLE
[Bug Report] Vue CLI test build with Vuetify fails with latest versions

### ISSUE THREAD

**Issue by gatkinsNZ** [vuetifyjs/vue-cli-plugins#164]
### Environment
vue-cli 4.2.3
vue-cli-plugin-vuetify 2.0.5
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
$ vue create test-app
$ cd test-app
$ vue add vuetify
$ node_modules\\.bin\vue-cli-service build --mode test

### Expected Behavior
App builds successfully under Test mode

### Actual Behavior
App fails to build with 104 "Failed to resolve loader: null-loader" errors

### Other comments
App does successfully build using dev or production mode.

I see the vuetify plugin has a description saying its for vue-cli 3, so does it not yet support vue-cli 4 (which has been out quite a while now, and I see v4.2 solves a "critical CORS vulnerability")?

**Comment by Bastczuak** [comment]
@gatkinsNZ I have the same problem. Do you have a .env.test file in your root directory? If so be sure to set `NODE_ENV=production`! Or maybe you somehow set the `NODE_ENV` somewhere else? It has to be `production`!!!! This was my trap.

**Comment by gatkinsNZ** [comment]
@Bastczuak Your right, that fixed my problem. Thanks for your help!

**Comment by M3psipax** [comment]
I have this same issue, but setting NODE_ENV to production doesn't work for me.

**Comment by ChandruCR** [comment]
make sure you unset NODE_ENV before serving.

for some reason if NODE_ENV is already set in environment variables then development server doesn't start.
so if you have done 
```export NODE_ENV=****```
then do
```unset NODE_ENV```
