### ISSUE TITLE
"isMobile" Fails with an "breakpoint" Property

### ISSUE THREAD

**Issue by rashadrivera** [vuetifyjs/vue-cli-plugins#171]
I'm getting an exception in the isMobile method.  It is caused because the breakpoint property is undefined.  Below is the error's point of failure.  I'm using **vuetify 2.2.15**.

```
isMobile: function isMobile() {
      // Guard against SSR render
      // https://github.com/vuetifyjs/vuetify/issues/7410
      if (this.$vuetify.breakpoint.width === 0) return false;
      return this.$vuetify.breakpoint.width < parseInt(this.mobileBreakpoint, 10);
    }
```
At runtime, the _breakpoint_ property is undefined and fails on the _if_ statement.

**Comment by rashadrivera** [comment]
I figured it out, but it is a weird error to receive.  Because I'm using class components and forgot to apply the **@Component** decorator to my class, I started to receive this error.  I was also receiving a host of other errors too.

The weird thing is that the content would partially render; making it difficult to identify the issue.

**Comment by yoeko** [comment]
Hello.
Can you please share how did you figure this out ?
I'm facing this 
**TypeError: Cannot read properties of undefined (reading 'breakpoint')
    at VueComponent.isMobile**
