### ISSUE TITLE
[Bug Report] missing js-beautify vuetify-storybook

### ISSUE THREAD

**Issue by Renato66** [vuetifyjs/vue-cli-plugins#172]
### Environment
**Browsers:** Chromium 80.0.3987.87
**OS:** Linux

### Steps to reproduce
* Create new vue project
* `vue add vuetify`
* `vue add vuetify-storybook`
* yarn run serve:storybook

### Expected Behavior
Storybook page

### Actual Behavior
```
ERROR in ./.storybook/addon-show-vue-markup/decorator.js
Module not found: Error: Can't resolve 'js-beautify' in '/Users/renato.vicente/Desktop/projetos/Morpheus.Client/.storybook/addon-show-vue-markup'
 @ ./.storybook/addon-show-vue-markup/decorator.js 3:0-35 12:14-22
 @ ./.storybook/addon-show-vue-markup/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
```

### Reproduction Link

**Comment by phivk** [comment]
also reported in `vue-cli-plugin-vuetify-storybook` plugin repo:
https://github.com/vuetifyjs/vue-cli-plugin-vuetify-storybook/issues/1

**Comment by phivk** [comment]
as a workaround I installed `js-beautify` manually:

`yarn add js-beautify`
