### ISSUE TITLE
[Bug Report] TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by tobias74** [vuetifyjs/vue-cli-plugins#176]
### Environment

**Browsers:** Other
**OS:** Linux

### Steps to reproduce
when running "vue add vuetify" I get the error-message:

🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at toPropertyHash (/usr/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:19:40)
    at Array.map (<anonymous>)
    at injectOptions (/usr/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:20:42)
    at newTransform (/usr/lib/node_modules/@vue/cli/node_modules/vue-jscodeshift-adapter/src/jscodeshift-mode.js:9:14)
    at runCodemod (/usr/lib/node_modules/@vue/cli/lib/util/runCodemod.js:29:26)
    at /usr/lib/node_modules/@vue/cli/lib/Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (/usr/lib/node_modules/@vue/cli/lib/Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (/usr/lib/node_modules/@vue/cli/lib/Generator.js:175:5)

### Expected Behavior
it works

### Actual Behavior
it throws error

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
too many required fields in this form. I am trying to tell you that your tail light is broken, and you make me jump through hoops :-)

**Comment by jacekkarczmarczyk** [comment]
Can't reproduce 

![image](https://user-images.githubusercontent.com/15625235/79446627-cb63bd00-7fde-11ea-9fd9-fbf43902d409.png)

You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by tobias74** [comment]
These are the steps to reproduce:

`
vue create my-app
cd my-app
vue add vuetify
`

Other properties of my setup: Ubuntu 16.04, NodeJS 13.13

@jacekkarczmarczyk do you really want me to open another issue?

**Comment by jacekkarczmarczyk** [comment]
Still no idea for example what options did you chose in `vue create` and `vue add`, if you provide this information it will make the reproduction much more accurate.
Can you also check on Node 12?

**Comment by tobias74** [comment]
I will try on Node 12,

up until now I found out the following:

As the error occurs in the file "injectOptions.js" I logged out the object that is illicitly missing the property "key" in the function "toPropertyHash":

Node {
  type: 'SpreadElement',
  start: 1724,
  end: 1730,
  loc: SourceLocation {
    start: Position { line: 92, column: 2, token: 194 },
    end: Position { line: 92, column: 8, token: 196 },
    lines: Lines {
      infos: [Array],
      mappings: [],
      cachedSourceMap: null,
      cachedTabWidth: undefined,
      length: 98,
      name: null
    },
    tokens: [
      [Object], [Object], [Object], [Object], [Object], [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      ... 117 more items
    ],
    indent: 2
  },
  argument: Node {
    type: 'Identifier',
    start: 1727,
    end: 1730,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      identifierName: 'App',
      lines: [Lines],
      tokens: [Array],
      indent: 2
    },
    name: 'App',
    optional: false,
    typeAnnotation: null
  }
}

The Node with type "SpreadElement" does not seem to have a "key"-property which the function 

`  const toPropertyHash = p => `${p.key.name}: ${j(p.value).toSource()}``

is relying on.

This is then the source for the error. Since "p.key" is undefined, "name" cannot be read.

But even if the p.key was set, the next error would be that it is also missing p.value.

My guess is that the function toPropertyHash is being called with a type that it is not expecting at all...

**Comment by tobias74** [comment]
Hmm, and right now I have to re-evaluate the reproduction-steps: 

All of a sudden it works when I run them in a completely clean folder. I am guessing that I somehow tempered with the App-Component and the generator has difficulties parsing it?
