### ISSUE TITLE
[Bug Report] Datatable CRUD not working

### ISSUE THREAD

**Issue by tauchvogel** [vuetifyjs/vue-cli-plugins#178]
### Environment

**Browsers:** Firefox 75.0
**OS:** Linux x86_64

### Steps to reproduce
I tried to reproduce the example "MY CRUD" Datatable (https://vuetifyjs.com/en/components/data-tables/#up-next) on my local server. I copied and pastet it into the files on my local machine.

The NEW ITEM button is not working, it is black and not blue. I also can not edit any entry.

But I can delete the items, with the delet button.

What's wrong with it?

### Expected Behavior
Should work normally

### Actual Behavior
Does not work

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
