### ISSUE TITLE
vue add vuetify success,but ERROR:You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.

### ISSUE THREAD

**Issue by mengqiui** [vuetifyjs/vue-cli-plugins#200]
@vue/cli：4.5.4
node：10.15.3

package.json:

{
  "name": "web-vuetify",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "vue-cli-plugin-vuetify": "~2.0.7"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
--------------------------------------------------------------------------------------------------------------

$ vue create web-vuetify
? Please pick a preset: (Use arrow keys)
? Please pick a preset: Default (Vue 3 Preview) ([Vue 3] babel, eslint)
? Pick the package manager to use when installing dependencies: (Use arrow keys)
? Pick the package manager to use when installing dependencies: NPM
✨  Creating project in C:\Users\81089\Desktop\web-vuetify.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

> yorkie@2.0.0 install C:\Users\81089\Desktop\web-vuetify\node_modules\yorkie
> node bin/install.js

setting up Git hooks
done

> core-js@3.6.5 postinstall C:\Users\81089\Desktop\web-vuetify\node_modules\core                                                                                                                -js
> node -e "try{require('./postinstall')}catch(e){}"

> ejs@2.7.4 postinstall C:\Users\81089\Desktop\web-vuetify\node_modules\ejs
> node ./postinstall.js

added 1228 packages from 918 contributors and audited 1231 packages in 281.023s
found 0 vulnerabilities

🚀  Invoking generators...
📦  Installing additional dependencies...

added 70 packages from 46 contributors and audited 1301 packages in 46.498s
found 0 vulnerabilities

⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project web-vuetify.
👉  Get started with the following commands:

 $ cd web-vuetify
 $ npm run serve
---------------------------------------------------------------------------------------------------------------
$ cd web-vuetify
---------------------------------------------------------------------------------------------------------------
$ vue add vuetify
 WARN  There are uncommitted changes in the current repository, it's recommended                                                                                                                 to commit or stash them first.
? Still proceed? (y/N) y
? Still proceed? Yes

📦  Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@2.0.7
updated 1 package and audited 1308 packages in 30.628s
found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: (Use arrow keys)
? Choose a preset: Prototype (rapid development)

🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, che                                                                                                                ck the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "                                                                                                                length" property first to verify at least 1 path exists.
    at Collection.get (C:\Users\81089\AppData\Roaming\npm\node_modules\@vue\cli\                                                                                                                node_modules\jscodeshift\src\Collection.js:213:13)
    at injectOptions (C:\Users\81089\AppData\Roaming\npm\node_modules\@vue\cli\l                                                                                                                ib\util\codemods\injectOptions.js:15:6)
    at runTransformation (C:\Users\81089\AppData\Roaming\npm\node_modules\@vue\c                                                                                                                li\node_modules\vue-codemod\dist\src\run-transformation.js:61:17)
    at Object.keys.forEach.file (C:\Users\81089\AppData\Roaming\npm\node_modules                                                                                                                \@vue\cli\lib\Generator.js:290:23)
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (C:\Users\81089\AppData\Roaming\npm\node_modules\@                                                                                                                vue\cli\lib\Generator.js:276:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/140

TL;DR - use Vue 2

**Comment by PachVerb** [comment]
> Duplicate of #140
> 
> TL;DR - use Vue 2

Why do you have to use vuE2, you can't use vuetify in vuE3

**Comment by DRoet** [comment]
no Vuetify is not compatible yet with Vue 2, see https://vuetifyjs.com/en/introduction/roadmap/

**Comment by jacekkarczmarczyk** [comment]
> no Vuetify is not compatible yet with Vue 2

Vue 3 ;)

**Comment by PachVerb** [comment]
> no Vuetify is not compatible yet with Vue 2, see https://vuetifyjs.com/en/introduction/roadmap/


> no Vuetify is not compatible yet with Vue 2, see https://vuetifyjs.com/en/introduction/roadmap/

Thank you, I see. But I'm talking vue3 here, It's compatible in Vue2

**Comment by DRoet** [comment]
whoops unfortunate typo 😅

**Comment by aviachn** [comment]
Add the following in main.js
`new Vue({ 
router,
store,
vuetify,
render: h => h(App) 
}).$mount("#app");`

**Comment by FotieMConstant** [comment]
I had this same issue and had to roll back to vue 2, apparently vue 3 doesn't support vuetify

**Comment by ungarson** [comment]
<img width="672" alt="Screenshot 2021-02-26 at 20 52 53" src="https://user-images.githubusercontent.com/13982759/109336566-a255bf00-7874-11eb-8f63-c0345c324e05.png">
Try choosing preset «Configure (advanced)»

This preset might work for you:
```
? Use a pre-made template? (will replace App.vue and HelloWorld.vue) No
? Use custom theme? No
? Use custom properties (CSS variables)? Yes
? Select icon font Material Design Icons
? Use fonts as a dependency (for Electron or offline)? No
? Use a-la-carte components? Yes
? Select locale English
```

**Comment by Daaayyy71** [comment]
> <img alt="Screenshot 2021-02-26 at 20 52 53" width="672" src="https://user-images.githubusercontent.com/13982759/109336566-a255bf00-7874-11eb-8f63-c0345c324e05.png">
> 
> Try choosing preset «Configure (advanced)»
> This preset might work for you:
> 
> ```
> ? Use a pre-made template? (will replace App.vue and HelloWorld.vue) No
> ? Use custom theme? No
> ? Use custom properties (CSS variables)? Yes
> ? Select icon font Material Design Icons
> ? Use fonts as a dependency (for Electron or offline)? No
> ? Use a-la-carte components? Yes
> ? Select locale English
> ```

still doesn't work
![image](https://user-images.githubusercontent.com/68411945/113272991-c6426f80-930e-11eb-9042-fc679a8eeaa6.png)

**Comment by EdsonCarvalho24** [comment]
Tenta mudar para vue 2 
Tenho a certeza que estás a usar vue 3 
E o vuetify só instala no vue 2.

**Comment by Daaayyy71** [comment]
> Tenta mudar para vue 2
> Tenho a certeza que estás a usar vue 3
> E o vuetify só instala no vue 2.

this version of Vuetify can be used only in vue2. https://vuetifyjs.com/en/introduction/roadmap/#in-development

**Comment by erkin7333** [comment]
? Choose a preset: Default (recommended)
Using newer version (^1.49.7), but this may cause build errors.
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.

Please help correct this error
