### ISSUE TITLE
Increase SASS compilation time by default when scaffolding new Vuetify project

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vue-cli-plugins#203]
https://vuetifyjs.com/en/customization/sass-variables/#sass-variables

On this page, docs says that it is possible to increase drastically SASS compilation by replacing this line:
```
import Vuetify from 'vuetify/lib
```
with this line:
```
import Vuetify from 'vuetify/lib/framework'
```

I know that there are some `vuetify-loader` limitations which may mute this gain, but I have found that they are not very common. IMO this performance gain should be enabled by default when scaffolding a new project using `vue-cli-plugin-vuetify`.

Related issues to this SASS compilation performance problem:
- https://github.com/vuetifyjs/vuetify/issues/12202#issuecomment-689767268
- https://github.com/vuetifyjs/vuetify/issues/11901
- https://github.com/vuetifyjs/vuetify/issues/9612

**Comment by joncfoo** [comment]
Additionally, the latter part of this comment needs to be applied when using TypeScript. https://github.com/vuetifyjs/vuetify-loader/issues/44#issuecomment-718089393
