### ISSUE TITLE
"Could not find a declaration file for module 'vuetify/lib/framework'."

### ISSUE THREAD

**Issue by some-user123** [vuetifyjs/vue-cli-plugins#228]
Adding vuetify to a typescript vue project (`vue add vuetify`) with a la carte components causes the error message "Could not find a declaration file for module 'vuetify/lib/framework'." when compiling this import:

```typescript
import Vuetify from 'vuetify/lib/framework'
```

even though the `shims-vuetify.d.ts` exists. It seems like it is ignored.

Any ideads?

It seems, I'm not alone: https://stackoverflow.com/questions/65172139/could-not-find-a-declaration-file-for-module-vuetify-lib-framework/65172140

**Comment by Raza9798** [comment]
same thing happen to me, what I did was stopped the development server and started again solved the issue
