### ISSUE TITLE
Question: in webpack-plugin, why @/sass/variables.scss is @import before vuetify's default styles.sass

### ISSUE THREAD

**Issue by wlf100220** [vuetifyjs/vue-cli-plugins#234]
Here is a confusing snippet of the `vue inspect` result:
```js
{
    prependData: '@import \'@/sass/variables.scss\';\n@import \'~vuetify/src/styles/styles.sass\';'
}
```
And your source code tells that
``` js
// vue-cli-plugin-vuetify/util/helpers.js

// Inject Vuetify styles at the end of user supplied
  data.push(`@import '~vuetify/src/styles/styles.sass${end}`)
```
If I'm not wrong, the purpose of `'@/sass/variables.scss'` is to overwrite *default variables*. But why it is `@import` before?

**Comment by KaelWD** [comment]
https://sass-lang.com/documentation/variables#default-values

**Comment by wlf100220** [comment]
@KaelWD Thank you! This rule is unusual.
