### ISSUE TITLE
[Bug Report] Vuetify Presets not working

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vue-cli-plugins#241]
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.182
**OS:** Linux x86_64

### Steps to reproduce
1. Clone the repo
2. yarn
3. yarn run serve

### Expected Behavior
Installed preset shall run as normal without any errors

### Actual Behavior
When we run the development server we are getting error of prependData.

### Reproduction Link
<a href="https://github.com/jd-0001/vuetify-preset" target="_blank">https://github.com/jd-0001/vuetify-preset</a>

### Other comments
When I checked the webpack config I guess we shall use additionalData instead of prependData.

**Comment by arrtchiu** [comment]
It looks as though #211 fixed this - making those same changes fixed the issue for me.

**Comment by arrtchiu** [comment]
The issue seems to be that the presets depend on `cli-plugin-utils` version `0.0.7`, but the fix is not there until `0.0.9`.

Unsure how to test this properly, but I think this is the fix: https://github.com/vuetifyjs/vue-cli-plugins/pull/256
