### ISSUE TITLE
Vue Add vuetify is having conflicting sass-loader 

### ISSUE THREAD

**Issue by faithfulojebiyi** [vuetifyjs/vue-cli-plugins#252]
![16153400481971512854974](https://user-images.githubusercontent.com/26503966/110562076-251a2c00-8149-11eb-8d01-f7dcdecfef20.jpg)

**Comment by ElijahKotyluk** [comment]
Please provide reproduction steps and the versions selected so that I can reproduce this issue and find a solution.
