### ISSUE TITLE
[Bug Report] vuetify overwrites the lang="" attribute in index.html and will set it to lang="en"

### ISSUE THREAD

**Issue by farhadnowzari** [vuetifyjs/vue-cli-plugins#274]
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce

just on a new vue project, run 
```
vue add vuetify
```

### Expected Behavior

It is expected that after adding vuetify to the project it doesn't change this value back to "en" because it causes a lot of issues with translators for users.

### Actual Behavior

by default vue has the lang attribute set to empty according to the following issue but after adding vuetify, it will replace the lang="" with lang="en"
https://github.com/vuejs/vue-cli/issues/5945

**Comment by jacekkarczmarczyk** [comment]
>  it doesn't change this value back to "en"

is doesn't "change this value back", it sets it to the language you have chosen in plugin options

**Comment by jacekkarczmarczyk** [comment]
imho setting lang to "" should be only the workaround for those who have problem with translators, not the default behaviour

**Comment by farhadnowzari** [comment]
This is not related to vuetify to change it. It should leave it out because it has already had a long discussion in `vue issues`.
Setting it to empty will let the browser to decide.
Having it to empty for anyone who doesn't care about the translation will not matter but setting it to a default lang for every other project who people care about translators have a huge impact.
When we had this issue with Vue and we did not know about it, users were complaining about the website and were doubting if the website they are reaching is fake.
A proposal would be vue asks about the default locale but it doesn't they've just set it to empty.
I think with vuetify it should be the same, it was an unexpected behaviour after that fix with vue.

**Comment by ElijahKotyluk** [comment]
If you don't want to use the presets you can select the `configure` option in the cli and it will prompt you for locale.

**Comment by farhadnowzari** [comment]
There is a config for the CLI? Ok I will try that.

**Comment by ElijahKotyluk** [comment]
I'm going to close this as this is currently the intended functionality and an option is provided to select locale if that is preferred. Feel free to open a feature request if you have any further suggestions, thank you.
