### ISSUE TITLE
`vue add vuetify` throws error due to `yarn add vue-cli-plugin-vuetify -D --tilde`

### ISSUE THREAD

**Issue by T45K** [vuetifyjs/vue-cli-plugins#284]
When I try to add vuetify using `vue add vuetify` command, it throws an error.
My Vue project consists of
- Vue 2
- TypeScript

## log
```sh
$ vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/Users/t45k/prog/vueitter/yarn-error.log".
error An unexpected error occurred: "https://registry.npm.taobao.org/rechoir/download/rechoir-0.6.2.tgz: Request failed \"503 Service Unavailable\"".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 ERROR  command failed: yarn add vue-cli-plugin-vuetify -D --tilde
```
## Environment
- MacOS Big Sur (w/ Intel CPU)
- vue/cli 4.5.13
- yarn 1.22.10

**Comment by KaelWD** [comment]
That would be a problem with the chinese NPM mirror, not us.

**Comment by debiru** [comment]
> `ERROR  command failed: yarn add vue-cli-plugin-vuetify -D --tilde`

I also encountered this error. After much investigation, I found that the cause was an outdated version of yarn. I changed from yarn 3.x to 4.x and the command was successfully executed.
