### ISSUE TITLE
Nuxt this.getOptions is not a function

### ISSUE THREAD

**Issue by f3ltron** [vuetifyjs/vue-cli-plugins#285]
My error:

<img width="877" alt="Screen Shot 2021-07-13 at 8 57 28 PM" src="https://user-images.githubusercontent.com/11556276/125544063-925f0ceb-cfe8-4cfe-8a2c-38b151dbeb64.png">

My config:

<img width="514" alt="Screen Shot 2021-07-13 at 8 57 43 PM" src="https://user-images.githubusercontent.com/11556276/125544086-184dc5fb-2f82-42d7-a88f-31fb675db504.png">

My vuetify options

<img width="359" alt="Screen Shot 2021-07-13 at 8 58 14 PM" src="https://user-images.githubusercontent.com/11556276/125544122-08ebba05-1ca6-4f1c-b4e0-631b29a03c26.png">

My package json:

<img width="616" alt="Screen Shot 2021-07-13 at 8 58 44 PM" src="https://user-images.githubusercontent.com/11556276/125544157-7858922e-1e21-44ee-9ebc-5ccbcdc77ac0.png">

**Comment by DRoet** [comment]
Nuxt is not compatible yet with webpack 5 loaders, make sure to pin your sass-loader to `10.2.0` and sass to `1.32.13`

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
