### ISSUE TITLE
No matching version found for the dependency `s^1.6.0` while install Vuetify from vue-cli

### ISSUE THREAD

**Issue by kennguyen0303** [vuetifyjs/vue-cli-plugins#305]
Hello,

When I run `vue add vuetify`, I encountered an error with the dependency `s@^1.6.0` which vuetify was trying to add. When I check with `npm view s`, the latest version of `s` is `1.0.0`. Hence, I'm wondering if anyone is having the same issue? 

![image](https://user-images.githubusercontent.com/60043570/141057070-de3a40cf-9c6b-4252-8b2d-e23158f94803.png)

![image](https://user-images.githubusercontent.com/60043570/141057245-0cb98957-72fd-4de0-bf2c-82eda46e928b.png)

**Comment by ElijahKotyluk** [comment]
Which preset did you select so that I can reproduce?

**Comment by kennguyen0303** [comment]
Hello, I'm badly sorry about this. Eventually, I made a mistake while typing and it has changed a dependency name from `neovis.js` to `s`. Hence the silly error. 

Everything is good for me now. Thank you for your time.
